name: "InHouse"

on:
  push:
    branches:
      master
jobs:
  build:
    runs-on: macos-latest  

    steps:
      - uses: actions/checkout@v2  
      - name: Run2 a one-line script
        run: echo Hello, world!  


